### ISSUE TITLE
Unable to read gef file

### ISSUE THREAD

**Issue by awa5114** [cemsbv/pygef#123]
Hello,

I have been trying to read a gef file using the following code:

```
from pygef import Cpt

Cpt(r"..\GO\46358_10.GEF")
```

Unfortunately I get an error:
```
thread '<unnamed>' panicked at 'python apply failed: Any(InvalidOperation("abs not supportedd for series of type Float64"))', src\lazy\apply.rs:35:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "C:\Users\921479\Desktop\GEO\Z002\notebooks\test_gef.py", line 5, in <module>
    Cpt(r"..\GO\46358_10.GEF")
  File "C:\Users\921479\Desktop\GEO\Z002\notebooks\.venv\lib\site-packages\pygef\cpt.py", line 159, in __init__
    parsed = _GefCpt(path)
  File "C:\Users\921479\Desktop\GEO\Z002\notebooks\.venv\lib\site-packages\pygef\gef.py", line 276, in __init__
    self.parse_data(self._headers, self._data, column_names)
  File "C:\Users\921479\Desktop\GEO\Z002\notebooks\.venv\lib\site-packages\polars\lazy\frame.py", line 299, in collect
    return pl.eager.frame.wrap_df(ldf.collect())
pyo3_runtime.PanicException: python apply failed: Any(InvalidOperation("abs not supportedd for series of type Float64"))
```

I think there is a problem in the `.collect()` statement when the cpt data is converted to a DataFrame. Has anyone come across this issue before? Does there exist a workaround? Thanks for your consideration.

**Comment by ritchie46** [comment]
See #121 

Update polars: `pip install polars==0.10.21`

**Comment by awa5114** [comment]
Thanks that worked.
