### ISSUE TITLE
Issue with plotting with Robertson classification

### ISSUE THREAD

**Issue by amo-mhp** [cemsbv/pygef#273]
Hi there,

I am a new user of the package pygef.

I sucessfully plotted a cpt but when I add "roberston" to the plotting function it returns an error:

````
cpt = Cpt(path)
a = cpt.plot("robertson")
a.show()


Traceback (most recent call last):
  File "C:\Users\amo.IPC\AppData\Local\Programs\Python\Python310\lib\site-packages\win32com\server\policy.py", line 303, in _Invoke_
    return self._invoke_(dispid, lcid, wFlags, args)
  File "C:\Users\amo.IPC\AppData\Local\Programs\Python\Python310\lib\site-packages\win32com\server\policy.py", line 308, in _invoke_
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
  File "C:\Users\amo.IPC\AppData\Local\Programs\Python\Python310\lib\site-packages\win32com\server\policy.py", line 637, in _invokeex_
    return func(*args)
  File "C:\Users\amo.IPC\AppData\Local\Programs\Python\Python310\lib\site-packages\xlwings\server.py", line 235, in CallUDF
    res = call_udf(script, fname, args, this_workbook, FromVariant(caller))
  File "C:\Users\amo.IPC\AppData\Local\Programs\Python\Python310\lib\site-packages\xlwings\udfs.py", line 539, in call_udf
    ret = func(*args)
  File "c:\Users\amo.IPC\OneDrive\02_docadmin\Software_and_Spreadsheets\Python\methods\testfile.py", line 11, in cpt
    a = cpt.plot("robertson")
  File "C:\Users\amo.IPC\AppData\Local\Programs\Python\Python310\lib\site-packages\pygef\cpt.py", line 301, in plot
    df = self.classify(
  File "C:\Users\amo.IPC\AppData\Local\Programs\Python\Python310\lib\site-packages\pygef\cpt.py", line 208, in classify
    df = robertson.classify(
  File "C:\Users\amo.IPC\AppData\Local\Programs\Python\Python310\lib\site-packages\pygef\robertson\__init__.py", line 39, in classify
    return iterate_robertson(
  File "C:\Users\amo.IPC\AppData\Local\Programs\Python\Python310\lib\site-packages\pygef\robertson\util.py", line 96, in iterate_robertson
    df["n"] = n
  File "C:\Users\amo.IPC\AppData\Local\Programs\Python\Python310\lib\site-packages\polars\internals\dataframe\frame.py", line 1401, in __setitem__
    raise TypeError(
TypeError: 'DataFrame' object does not support 'Series' assignment by index. Use 'DataFrame.with_columns'
````

any advise?

**Comment by tversteeg** [comment]
Unfortunately, we don't support the Robertson classification anymore. We've completely removed this in the newest version 0.8.0, which is now in alpha.
